/***************************************************************************************

	Copyright 2012 Greg Dennis

	   Licensed under the Apache License, Version 2.0 (the "License");
	   you may not use this file except in compliance with the License.
	   You may obtain a copy of the License at

		 http://www.apache.org/licenses/LICENSE-2.0

	   Unless required by applicable law or agreed to in writing, software
	   distributed under the License is distributed on an "AS IS" BASIS,
	   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	   See the License for the specific language governing permissions and
	   limitations under the License.
 
	File Name:		EntityRequestType.cs
	Namespace:		Manatee.Trello
	Class Name:		EntityRequestType
	Purpose:		Enumerates the various types of requests, including which kind
					of entity is submitting the request and the desired operation.

***************************************************************************************/

namespace Manatee.Trello
{
	public enum EntityRequestType
	{
		Unsupported,
		Action_Write_Delete,
		Action_Read_Refresh,
		Attachment_Write_Delete,
		Badges_Read_Refresh,
		Board_Read_Actions,
		Board_Write_AddList,
		Board_Write_AddOrUpdateMember,
		Board_Read_Cards,
		Board_Read_Checklists,
		Board_Write_Description,
		Board_Read_InvitedMembers,
		Board_Write_InviteMember,
		Board_Write_IsClosed,
		Board_Write_IsPinned,
		Board_Write_IsSubscribed,
		Board_Read_Lists,
		Board_Write_MarkAsViewed,
		Board_Read_Members,
		Board_Read_Memberships,
		Board_Write_Name,
		Board_Write_Organization,
		Board_Read_Refresh,
		Board_Write_RemoveMember,
		Board_Write_RescindInvitation,
		BoardPersonalPreferences_Read_Refresh,
		BoardPersonalPreferences_Write_ShowListGuide,
		BoardPersonalPreferences_Write_ShowSidebar,
		BoardPersonalPreferences_Write_ShowSidebarActivity,
		BoardPersonalPreferences_Write_ShowSidebarBoardActions,
		BoardPersonalPreferences_Write_ShowSidebarMembers,
		BoardPreferences_Write_AllowsSelfJoin,
		BoardPreferences_Write_Comments,
		BoardPreferences_Write_Invitations,
		BoardPreferences_Write_PermissionLevel,
		BoardPreferences_Read_Refresh,
		BoardPreferences_Write_ShowCardCovers,
		BoardPreferences_Write_Voting,
		Card_Read_Actions,
		Card_Write_AddAttachment,
		Card_Write_AddChecklist,
		Card_Write_AddComment,
		Card_Write_ApplyLabel,
		Card_Write_AssignMember,
		Card_Read_Attachments,
		Card_Read_CheckItems,
		Card_Read_Checklists,
		Card_Write_ClearNotifications,
		Card_Write_Delete,
		Card_Write_Description,
		Card_Write_DueDate,
		Card_Write_IsClosed,
		Card_Write_IsSubscribed,
		Card_Read_Labels,
		Card_Read_Members,
		Card_Write_Move,
		Card_Write_Name,
		Card_Write_Position,
		Card_Read_Refresh,
		Card_Write_RemoveLabel,
		Card_Write_RemoveMember,
		Card_Read_VotingMembers,
		Card_Write_WarnWhenUpcoming,
		CheckItem_Write_Delete,
		CheckItem_Write_Name,
		CheckItem_Write_Position,
		CheckItem_Read_Refresh,
		CheckItem_Write_State,
		CheckList_Write_AddCheckItem,
		CheckList_Write_Card,
		CheckList_Read_CheckItems,
		CheckList_Write_Delete,
		CheckList_Write_Name,
		CheckList_Write_Position,
		CheckList_Read_Refresh,
		Label_Read_Refresh,
		LabelNames_Write_Blue,
		LabelNames_Write_Green,
		LabelNames_Write_Orange,
		LabelNames_Write_Purple,
		LabelNames_Write_Red,
		LabelNames_Read_Refresh,
		LabelNames_Write_Yellow,
		List_Read_Actions,
		List_Write_AddCard,
		List_Read_Cards,
		List_Write_Delete,
		List_Write_IsClosed,
		List_Write_IsSubscribed,
		List_Write_Move,
		List_Write_Name,
		List_Write_Position,
		List_Read_Refresh,
		Member_Read_Actions,
		Member_Write_AvatarSource,
		Member_Write_Bio,
		Member_Read_Boards,
		Member_Read_Cards,
		Member_Write_ClearNotifications,
		Member_Write_CreateBoard,
		Member_Write_CreateOrganizations,
		Member_Write_FullName,
		Member_Write_Initials,
		Member_Read_InvitedBoards,
		Member_Read_InvitedOrganizations,
		Member_Read_Notifications,
		Member_Read_Organization,
		Member_Write_PinBoard,
		Member_Read_Refresh,
		Member_Write_RescindVoteForCard,
		Member_Read_Sessions,
		Member_Read_Tokens,
		Member_Write_UnpinBoard,
		Member_Write_Username,
		Member_Write_VoteForCard,
		MemberPreferences_Write_ColorBlind,
		MemberPreferences_Write_MinutesBeforeDeadlineToNotify,
		MemberPreferences_Write_MinutesBetweenSummaries,
		MemberPreferences_Read_Refresh,
		MemberPreferences_Write_SendSummaries,
		MemberSession_Write_Delete,
		Notification_Write_IsUnread,
		Notification_Read_Refresh,
		Organization_Read_Actions,
		Organization_Write_AddOrUpdateMember,
		Organization_Read_Boards,
		Organization_Write_CreateBoard,
		Organization_Write_Delete,
		Organization_Write_Description,
		Organization_Write_DisplayName,
		Organization_Read_InvitedMembers,
		Organization_Write_InviteMember,
		Organization_Read_Members,
		Organization_Read_Memberships,
		Organization_Write_Name,
		Organization_Read_Refresh,
		Organization_Write_RemoveMember,
		Organization_Write_RescindInvitation,
		Organization_Write_Website,
		OrganizationMembership_Read_Refresh,
		OrganizationPreferences_Write_AssociatedDomain,
		OrganizationPreferences_Write_ExternalMembersDisabled,
		OrganizationPreferences_Write_OrgInviteRestrict,
		OrganizationPreferences_Write_OrgVisibleBoardVisibility,
		OrganizationPreferences_Write_PermissionLevel,
		OrganizationPreferences_Write_PrivateBoardVisibility,
		OrganizationPreferences_Write_PublicBoardVisibility,
		OrganizationPreferences_Read_Refresh,
		Service_Read_Me,
		Service_Read_Search,
		Service_Read_SearchMembers,
		Token_Write_Delete,
		Token_Read_Refresh,
	}
}