using System.Threading;
using System.Threading.Tasks;

namespace Manatee.Trello
{
	/// <summary>
	/// A collection of boards.
	/// </summary>
	public interface IBoardCollection : IReadOnlyBoardCollection
	{
		/// <summary>
		/// Creates a new board.
		/// </summary>
		/// <param name="name">The name of the board to create.</param>
		/// <param name="source">A board to use as a template.</param>
		/// <returns>The <see cref="Board"/> generated by Trello.</returns>
		Task<IBoard> Add(string name, IBoard source = null, CancellationToken ct = default(CancellationToken));
	}
}