using System.Threading.Tasks;

namespace Manatee.Trello
{
	/// <summary>
	/// A collection of checklist items.
	/// </summary>
	public interface ICheckItemCollection : IReadOnlyCheckItemCollection
	{
		/// <summary>
		/// Creates a new checklist item.
		/// </summary>
		/// <param name="name">The name of the checklist item to add.</param>
		/// <returns>The <see cref="ICheckItem"/> generated by Trello.</returns>
		Task<ICheckItem> Add(string name);
	}
}