using System.Threading;
using System.Threading.Tasks;

namespace Manatee.Trello
{
	/// <summary>
	/// A collection of comment reactions.
	/// </summary>
	public interface ICommentReactionCollection : IReadOnlyCollection<ICommentReaction>
	{
		/// <summary>
		/// Creates a new comment reaction.
		/// </summary>
		/// <param name="emoji">The <see cref="Emoji"/> to add.</param>
		/// <param name="ct">(Optional) A cancellation token.</param>
		/// <returns>The <see cref="ICommentReaction"/> generated by Trello.</returns>
		Task<ICommentReaction> Add(Emoji emoji, CancellationToken ct = default);
	}
}