using System.Threading;
using System.Threading.Tasks;

namespace Manatee.Trello
{
	/// <summary>
	/// A collection of comment reactions.
	/// </summary>
	public interface ICommentReactionCollection : IReadOnlyCollection<ICommentReaction>
	{
		/// <summary>
		/// Creates a new comment reaction.
		/// </summary>
		/// <param name="comment">The <see cref="IAction"/> comment to which to add the reaction.  Must be of type <see cref="ActionType.CommentCard"/></param>
		/// <param name="emoji">The <see cref="Emoji"/> to add.</param>
		/// <param name="ct">(Optional) A cancellation token.</param>
		/// <returns>The <see cref="ICommentReaction"/> generated by Trello.</returns>
		Task<ICommentReaction> Add(IAction comment, Emoji emoji, CancellationToken ct = default(CancellationToken));
	}
}