using System.Threading;
using System.Threading.Tasks;

namespace Manatee.Trello
{
	/// <summary>
	/// A collection of <see cref="ISticker"/>s.
	/// </summary>
	public interface IMemberStickerCollection
	{
        /// <summary>
        /// Adds a <see cref="ISticker"/> to a <see cref="IMember"/>'s custom sticker set by uploading data.
        /// </summary>
        /// <param name="filePath">The path of the file to attach.</param>
        /// <param name="name">A name for the sticker.</param>
        /// <param name="ct">(Optional) A cancellation token for async processing.</param>
        /// <returns>The <see cref="ISticker"/> generated by Trello.</returns>
        Task<ISticker> Add(string filePath, string name, CancellationToken ct = default);
	}
}