using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Manatee.Trello.Internal.DataAccess;
using Manatee.Trello.Internal.Validation;
using Manatee.Trello.Json;

namespace Manatee.Trello
{
	/// <summary>
	/// A collection of board memberships.
	/// </summary>
	public class BoardMembershipCollection : ReadOnlyBoardMembershipCollection, IBoardMembershipCollection
	{
		internal BoardMembershipCollection(Func<string> getOwnerId, TrelloAuthorization auth)
			: base(getOwnerId, auth)
		{
		}

		/// <summary>
		/// Adds a member to a board with specified privileges.
		/// </summary>
		/// <param name="member">The member to add.</param>
		/// <param name="membership">The membership type.</param>
		/// <param name="ct">(Optional) A cancellation token for async processing.</param>
		/// <returns>The <see cref="IBoardMembership"/> generated by Trello.</returns>
		public async Task<IBoardMembership> Add(IMember member, BoardMembershipType membership, CancellationToken ct = default)
		{
			var error = NotNullRule<IMember>.Instance.Validate(null, member);
			if (error != null)
				throw new ValidationException<IMember>(member, new[] {error});

			var json = TrelloConfiguration.JsonFactory.Create<IJsonBoardMembership>();
			json.Member = ((Member) member).Json;
			json.MemberType = membership;

			var endpoint = EndpointFactory.Build(EntityRequestType.Board_Write_AddOrUpdateMember, new Dictionary<string, object> {{"_id", OwnerId}, {"_memberId", member.Id}});
			var newData = await JsonRepository.Execute(Auth, endpoint, json, ct);

			if (TrelloConfiguration.EnableConsistencyProcessing &&
			    member.Boards is ReadOnlyCollection<IBoard> boardCollection)
			{
				var board = TrelloConfiguration.Cache.OfType<IBoard>().FirstOrDefault(b => b.Id == OwnerId);
				if (board != null)
					boardCollection.Items.Add(board);
			}

			return new BoardMembership(newData, OwnerId, Auth);
		}

		/// <summary>
		/// Removes a member from a board.
		/// </summary>
		/// <param name="member">The member to remove.</param>
		/// <param name="ct">(Optional) A cancellation token for async processing.</param>
		public async Task Remove(IMember member, CancellationToken ct = default)
		{
			var error = NotNullRule<IMember>.Instance.Validate(null, member);
			if (error != null)
				throw new ValidationException<IMember>(member, new[] {error});

			var endpoint = EndpointFactory.Build(EntityRequestType.Board_Write_RemoveMember, new Dictionary<string, object> {{"_id", OwnerId}, {"_memberId", member.Id}});
			await JsonRepository.Execute(Auth, endpoint, ct);

			if (TrelloConfiguration.EnableConsistencyProcessing &&
			    member.Boards is ReadOnlyCollection<IBoard> boardCollection)
			{
				var board = TrelloConfiguration.Cache.OfType<IBoard>().FirstOrDefault(b => b.Id == OwnerId);
				if (board != null)
					boardCollection.Items.Remove(board);
			}
		}
	}
}