/***************************************************************************************

	Copyright 2014 Greg Dennis

	   Licensed under the Apache License, Version 2.0 (the "License");
	   you may not use this file except in compliance with the License.
	   You may obtain a copy of the License at

		 http://www.apache.org/licenses/LICENSE-2.0

	   Unless required by applicable law or agreed to in writing, software
	   distributed under the License is distributed on an "AS IS" BASIS,
	   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	   See the License for the specific language governing permissions and
	   limitations under the License.
 
	File Name:		CheckListCollection.cs
	Namespace:		Manatee.Trello
	Class Name:		CheckListCollection
	Purpose:		Collection objects for CheckLists.

***************************************************************************************/

using System.Collections.Generic;
using System.Linq;
using Manatee.Trello.Exceptions;
using Manatee.Trello.Internal.Caching;
using Manatee.Trello.Internal.DataAccess;
using Manatee.Trello.Internal.Validation;
using Manatee.Trello.Json;

namespace Manatee.Trello
{
	/// <summary>
	/// A read-only collection of checklists.
	/// </summary>
	public class ReadOnlyCheckListCollection : ReadOnlyCollection<CheckList>
	{
		internal ReadOnlyCheckListCollection(string ownerId)
			: base(ownerId) {}

		/// <summary>
		/// Implement to provide data to the collection.
		/// </summary>
		protected override sealed void Update()
		{
			var endpoint = EndpointFactory.Build(EntityRequestType.CheckList_Read_Refresh, new Dictionary<string, object> {{"_id", OwnerId}});
			var newData = JsonRepository.Execute<List<IJsonCheckList>>(TrelloAuthorization.Default, endpoint);

			Items.Clear();
			Items.AddRange(newData.Select(jc => jc.GetFromCache<CheckList>()));
		}
	}

	/// <summary>
	/// A collection of checklists.
	/// </summary>
	public class CheckListCollection : ReadOnlyCheckListCollection
	{
		internal CheckListCollection(string ownerId)
			: base(ownerId) {}

		/// <summary>
		/// Creates a new checklist.
		/// </summary>
		/// <param name="name">The name of the checklist to add.</param>
		/// <returns>The <see cref="CheckList"/> generated by Trello.</returns>
		public CheckList Add(string name)
		{
			var error = NotNullOrWhiteSpaceRule.Instance.Validate(null, name);
			if (error != null)
				throw new ValidationException<string>(name, new[] { error });

			var json = TrelloConfiguration.JsonFactory.Create<IJsonCheckList>();
			json.Name = name;

			var endpoint = EndpointFactory.Build(EntityRequestType.Card_Write_AddChecklist);
			var newData = JsonRepository.Execute(TrelloAuthorization.Default, endpoint, json);

			return new CheckList(newData, true);
		}
	}
}