/***************************************************************************************

	Copyright 2015 Greg Dennis

	   Licensed under the Apache License, Version 2.0 (the "License");
	   you may not use this file except in compliance with the License.
	   You may obtain a copy of the License at

		 http://www.apache.org/licenses/LICENSE-2.0

	   Unless required by applicable law or agreed to in writing, software
	   distributed under the License is distributed on an "AS IS" BASIS,
	   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	   See the License for the specific language governing permissions and
	   limitations under the License.
 
	File Name:		CheckListCollection.cs
	Namespace:		Manatee.Trello
	Class Name:		CheckListCollection
	Purpose:		Collection objects for CheckLists.

***************************************************************************************/

using System.Collections.Generic;
using System.Linq;
using Manatee.Trello.Exceptions;
using Manatee.Trello.Internal;
using Manatee.Trello.Internal.Caching;
using Manatee.Trello.Internal.DataAccess;
using Manatee.Trello.Internal.Validation;
using Manatee.Trello.Json;

namespace Manatee.Trello
{
	/// <summary>
	/// A read-only collection of checklists.
	/// </summary>
	public class ReadOnlyCheckListCollection : ReadOnlyCollection<CheckList>
	{
		internal ReadOnlyCheckListCollection(Card card, TrelloAuthorization auth)
			: base(() => card.Id, auth) {}

		/// <summary>
		/// Retrieves a check list which matches the supplied key.
		/// </summary>
		/// <param name="key">The key to match.</param>
		/// <returns>The matching check list, or null if none found.</returns>
		/// <remarks>
		/// Matches on CheckList.Id and CheckList.Name.  Comparison is case-sensitive.
		/// </remarks>
		public CheckList this[string key] => GetByKey(key);

		/// <summary>
		/// Implement to provide data to the collection.
		/// </summary>
		protected sealed override void Update()
		{
			var endpoint = EndpointFactory.Build(EntityRequestType.Card_Read_CheckLists, new Dictionary<string, object> {{"_id", OwnerId}});
			var newData = JsonRepository.Execute<List<IJsonCheckList>>(Auth, endpoint);

			Items.Clear();
			Items.AddRange(newData.Select(jc =>
				{
					var checkList = jc.GetFromCache<CheckList>(Auth);
					checkList.Json = jc;
					return checkList;
				}));
		}

		private CheckList GetByKey(string key)
		{
			return this.FirstOrDefault(cl => key.In(cl.Id, cl.Name));
		}
	}

	/// <summary>
	/// A collection of checklists.
	/// </summary>
	public class CheckListCollection : ReadOnlyCheckListCollection
	{
		internal CheckListCollection(Card card, TrelloAuthorization auth)
			: base(card, auth) {}

		/// <summary>
		/// Creates a new checklist, optionally by copying a checklist.
		/// </summary>
		/// <param name="name">The name of the checklist to add.</param>
		/// <param name="source">A checklist to use as a template.</param>
		/// <returns>The <see cref="CheckList"/> generated by Trello.</returns>
		public CheckList Add(string name, CheckList source = null)
		{
			var error = NotNullOrWhiteSpaceRule.Instance.Validate(null, name);
			if (error != null)
				throw new ValidationException<string>(name, new[] { error });

			var json = TrelloConfiguration.JsonFactory.Create<IJsonCheckList>();
			json.Name = name;
			var jsonCard = TrelloConfiguration.JsonFactory.Create<IJsonCard>();
			jsonCard.Id = OwnerId;
			json.Card = jsonCard;
			if (source != null)
				json.CheckListSource = source.Json;

			var endpoint = EndpointFactory.Build(EntityRequestType.Card_Write_AddChecklist);
			var newData = JsonRepository.Execute(Auth, endpoint, json);

			return new CheckList(newData, Auth);
		}
	}
}