using System;
using System.Threading;
using System.Threading.Tasks;
using Manatee.Trello.Internal.DataAccess;
using Manatee.Trello.Internal.Validation;
using Manatee.Trello.Json;

namespace Manatee.Trello
{
	/// <summary>
	/// A collection of cards.
	/// </summary>
	public class CommentReactionCollection : ReadOnlyCommentReactionCollection, ICommentReactionCollection
	{
		internal CommentReactionCollection(Func<string> getOwnerId, TrelloAuthorization auth)
			: base(typeof (List), getOwnerId, auth) {}

		/// <summary>
		/// Creates a new comment reaction.
		/// </summary>
		/// <param name="comment">The <see cref="IAction"/> comment to which to add the reaction.  Must be of type <see cref="ActionType.CommentCard"/></param>
		/// <param name="emoji">The <see cref="Emoji"/> to add.</param>
		/// <param name="ct">(Optional) A cancellation token.</param>
		/// <returns>The <see cref="ICommentReaction"/> generated by Trello.</returns>
		public async Task<ICommentReaction> Add(IAction comment, Emoji emoji, CancellationToken ct = default(CancellationToken))
		{
			var error = NotNullRule<IAction>.Instance.Validate(null, comment);
			if (error != null)
				throw new ValidationException<IAction>(comment, new[] {error});
			error = RequireCommentRule.Instance.Validate(null, comment);
			if (error != null)
				throw new ValidationException<IAction>(comment, new[] {error});

			var json = TrelloConfiguration.JsonFactory.Create<IJsonCommentReaction>();
			json.Emoji = emoji;

			var endpoint = EndpointFactory.Build(EntityRequestType.List_Write_AddCard);
			var newData = await JsonRepository.Execute(Auth, endpoint, json, ct);

			return new CommentReaction(newData, Auth);
		}
	}
}