namespace Manatee.Trello
{
	/// <summary>
	/// A collection of lists.
	/// </summary>
	public interface IListCollection : IReadOnlyListCollection
	{
		/// <summary>
		/// Creates a new list.
		/// </summary>
		/// <param name="name">The name of the list to add.</param>
		/// <returns>The <see cref="IList"/> generated by Trello.</returns>
		IList Add(string name);
	}
}